apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: employee-management-project
  namespace: argocd

spec:
  description: Employee Management GitOps Project

  sourceRepos:
    - https://github.com/Rishivardan/employee-management-system.git

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

    - namespace: staging
      server: https://kubernetes.default.svc

    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
