replicaCount: 2

image:
  repository: rishiadl29/employee-management-system
  tag: "v38"
  pullPolicy: Always


service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080


config:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: employee_management
  DB_USER: employee_user


secret:
  DB_PASSWORD: employee123


mysql:
  image: mysql:8
  rootPassword: root123
  database: employee_management
  user: employee_user
  password: employee123
  port: 3306
  storage: 1Gi


ingress:
  enabled: false
  className: nginx
  host: employee.local
  path: /
  pathType: Prefix


resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"


livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10


readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


podAnnotations: {}

podSecurityContext: {}

volumeMounts: []

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}