{{- if .Values.ingress.enabled }}
{{- $root := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "employee-management-chart.fullname" . }}
  labels:
{{ include "employee-management-chart.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "employee-management-chart.fullname" $root }}
                port:
                  number: {{ $root.Values.service.port }}
{{- end }}
{{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
