apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-management-chart.fullname" . }}-secret
  labels:
{{ include "employee-management-chart.labels" . | indent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
