apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-management-chart.fullname" . }}
  labels:
{{ include "employee-management-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "employee-management-chart.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
